spring.application.name=Warsha


spring.datasource.url=jdbc:mysql://localhost:3306/warshaDB
spring.datasource.username=root
spring.datasource.password=Lalagado@24922

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
