# DataSource (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/warshaDB
spring.datasource.username=root
spring.datasource.password=Lalagado@24922

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=${PORT:9000}
server.forward-headers-strategy=framework

# Session
server.servlet.session.timeout=30m

server.error.include-message=always